name: Continuous integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  release:
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    uses: ./.github/workflows/release.yml
    secrets: inherit
